name: ushop
description: Flutter ecommerce app (Ushop).

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  http: ^0.13.4
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11
  hydrated_bloc: ^8.1.0
  share_plus: ^4.0.10
  validators: ^3.0.0
  stream_transform: ^2.0.0
  line_icons: ^2.0.0
  flutter_rating_bar: ^4.0.1
  easy_image_viewer: ^1.1.0
  date_time_picker: ^2.1.0
  image_picker: ^0.8.3+3
  easy_localization: ^3.0.1
  connectivity_wrapper: ^1.1.0
  flutter_local_notifications: ^9.9.1
  url_launcher: ^6.1.5
  flutter_launcher_icons: ^0.10.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_background: "#ffffff"
  ios: true
  image_path: "assets/images/others/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/product_images/
    - assets/images/news_images/
    - assets/translations/


